name: CI

on:
  push:
    branches: [ "task7" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven


      - name: Build application
        run: |
          mvn install --no-transfer-progress